#!/bin/sh

man() {
    echo """
    All of the arguments are case insensitive.

    -x                           Install Bifrost Link Dependencies
    -p|--project                 Opens the Projects Menu
    -p| <PROJECT NAME>           Create a New Project

    -d|--debug                   Enter Debugging Mode

    -v|--version                 Check the Current Version
    -u|--update                  Update Bifrost Link
    -U|--force-update            Force Update [Can Delete All Projects]
    
    """
}
