#!/bin/sh

bridge='export PATH="$PATH:$HOME/.local/bin:/bin:/usr/local/bin:/usr/bin:/bin:$HOME/.local/bin"'

origin=~/.local/share/Bifrost
location=$(pwd)
#transfer=$(mv -f $location $origin)

build () {
    echo
    echo "\033[0;37m Building the Bifrost Bridge..\033[0m"
    echo
    sleep 2
    cp Bifrost.c bifrost
    chmod +x bifrost
    mkdir -p ~/.local/bin
    mv bifrost ~/.local/bin
    chmod +x ~/.local/bin/bifrost
    rm -rf "$origin"
    #mkdir $origin > /dev/null 2>&1
    #transfer
    mv -f "$location" "$origin"

    # Check if the line already exists in ~/.bashrc and append it if not
    if ! grep -qF "$bridge" ~/.bashrc; then
        echo "$bridge" >> ~/.bashrc
    fi

    # Check if the line already exists in ~/.zshrc and append it if not
    if ! grep -qF "$bridge" ~/.zshrc; then
        echo "$bridge" >> ~/.zshrc
    fi
    
    echo "\033[1;32m Operation Completed Successfully.\033[0m"
    echo
    echo " Now you can use the Bifrost Link simply by typing\033[1;36m bifrost\033[0m on your terminal."
    }

# Build Bifrost Bridge
build