#!/bin/sh

. ./.core/TRACKER


build () {
    echo
    echo "\033[0;37m Building the Bifrost Bridge..\033[0m"
    echo
    sleep 2
    chmod +x ./.core/SIGNAL/bifrost
    mkdir -p $alpha
    rm -rf $alpha/bifrost
    cp -f ./.core/SIGNAL/bifrost $alpha/bifrost
    sed -i "3s#.*#. $omega/.core/ASSEMBLER#" $alpha/bifrost
    cp -r ./projects/* $projects_folder
    rm -rf ./projects

    rm -rf $omega
    cp -rf $currentdir $omega

    # Check if the line already exists in ~/.bashrc and append it if not
    if ! grep -qF "$export_path" ~/.bashrc; then
        echo "$export_path" >> ~/.bashrc
    fi

    # Check if the line already exists in ~/.zshrc and append it if not
    if ! grep -qF "$export_path" ~/.zshrc; then
        echo "$export_path" >> ~/.zshrc
    fi
    
    echo "\033[1;32m Operation Completed Successfully.\033[0m"
    echo
    echo " Now you can use the Bifrost Link simply by typing\033[1;36m bifrost\033[0m on your terminal."
    exit 0
}

# Build Bifrost Bridge
build





