#!/bin/bash

# IP range allowed on target. For domains please include the full domain address (http:// or https://)
target_domain='127.0.0.1'
target_username=
target_password=

# Modification below here is not recommended.
# Only do it if you know what you're doing, otherwise it might break something.
ip="$target_domain"
ip_range="$target_domain"

target="$target_domain"