#!/bin/sh

refresh() {
    clear
    logo
    }

udev() { # refresh but with data kept
    echo "    $yellow2 This feature is currently under development.$end"
    echo
    sleep 2
    echo "    $white Reinitializing..$end"
    sleep 2
    refresh
    target_data
    menu
    }

menu () {
    echo
    echo "$negative Menu $end"
    echo
    echo "  1) Network Scan"
    echo "  2) Find DC IP"
    echo "  3) Zone Transfer"
    echo "  4) List Guest Access on SMB Share"
    echo "  5)$dim Enumerate LDAP $end"
    echo "  6)$dim Find User List $end"
    echo "  7)$dim Poisoning $end"
    echo "  8)$dim Coerce $end"
    echo
    echo "  E) Exit"
    echo
    echo "  L) Show Legend"
    echo "  X) Install Dependencies"
    echo
    echo "  C) Change Credentials" # Have to create a file called credentials that read the file target and modify it once created all arguments from the 8 menu options
    echo
    echo -n "     Choose one of the above options: "
    menu_select
    }

menu_select  () {
    read selection
    echo
    case $selection in
    1) network_scan;;
    2) find_dc_ip;;
    3) zone_transfer;;
    4) list_guest_access_smb_share;;
    5) udev;;
    6) udev;;
    7) udev;;
    8) udev;;
    [Ee]) credits; exit;;
    [Ll]) legend;;
    [Xx]) dependencies; menu_return;;
    [Cc]) udev;;
    *) error_menu ; menu_return;;
    esac
    }

menu_return (){
    while true; do
        printf "     Would you like to go back to the main menu? $white[Y/n]$end: " && read input
        case $input in
            "y" | "Y" | "1" | "")
                echo
                echo "    $dim Reinitializing the Bifrost..$end"
                sleep 3
                start
                ;;
            "n" | "N" | "2" | "")
                echo
                credits
                exit 1
                ;;
            *)
                echo
                error
                echo
                menu_select
        esac
    done
    }

error_argument() {
        echo -n "\033[2A\033[0K $red    Incorrect selection. Try again: $end"
        while true; do
            read -p ""  choice
        done
        echo
        }

error_menu() {
        echo -n "\033[2A\033[0K $red    Incorrect selection. Try again: $end"
        menu_select
        echo
        }