#!/bin/sh

# Function to handle command-line arguments
handle_arguments() {
    if [ $# -eq 0 ]; then
        no_project
        return
    fi

    while [ $# -gt 0 ]; do
        case "$1" in
            -m|-h)
                man
                exit 1
                ;;
            --x)
                echo
                dependencies
                exit 1
                ;;
            -p|--project)
                shift  # Consume the -p flag
                if [ $# -eq 0 ]; then
                    projects_menu
                fi
                project_name="$1"
                
                # Check if the folder already exists
                if [ -d "$omega/projects/$project_name" ]; then
                    project_found
                else
                    project_create
                fi
                ;;
            -d|--debug)
                start
                ;;
            -v|--version)
                print_version
                exit 0
                ;;
            -u|--update)
                echo
                update
                exit 0
                ;;
            -U|--force-update)
                echo
                force_update
                exit 0
                ;;
            *)
                echo
                echo "Invalid argument. Use the $yellow2-H$end or $yellow2-M$end flag to see all the available commands."
                exit 1
                ;;
        esac
        shift
    done
}