#!/bin/sh

. ~/.local/share/bifrost/.core/TRACKER

# Assets
. $omega/.assets/CSS
. $omega/.assets/LOGO

# Menu
. $omega/.menu/MAIN
. $omega/.menu/FIND-DCIP
. $omega/.menu/ZONE-TRANSFER
. $omega/.menu/LGA-SMB-SHARE
. $omega/.menu/FIND-USER-LIST
. $omega/.menu/POISONING
. $omega/.menu/COERCE
. $omega/.menu/LDAP-ENUM

# Info

. $omega/.info/CREDITS
. $omega/.info/LEGEND
. $omega/.info/MAN

# Core
. $omega/.core/CONTROL
. $omega/.core/DEPENDENCIES
. $omega/.core/TARGET
. $omega/.core/PROJECTS
. $omega/.core/ARGUMENTS
. $omega/.core/UPDATER

start () {
    #sudoreq
    clear
    logo
    print_version
    target_data
    menu
    menu_select
}

