#!/bin/sh

# origin=~/.local/bin/bifrost

# omega=~/.local/share/bifrost # Final Directory Destination of the Package Folder
#. $omega/.core/ASSEMBLER

bridge_build() {
    omega="." # Debug
}

bridge_set() {
    omega=~/.local/share/bifrost # Final Directory Destination of the Package Folder
}

# Assets
. $omega/.assets/CSS
. $omega/.assets/LOGO

# Menu
. $omega/.menu/MAIN
. $omega/.menu/FIND-DCIP
. $omega/.menu/ZONE-TRANSFER
. $omega/.menu/LGA-SMB-SHARE
. $omega/.menu/FIND-USER-LIST
. $omega/.menu/POISONING
. $omega/.menu/COERCE
. $omega/.menu/LDAP-ENUM

# Info

. $omega/.info/CREDITS
. $omega/.info/LEGEND
. $omega/.info/MAN

# Core
. $omega/.core/CONTROL
. $omega/.core/DEPENDENCIES
. $omega/.core/TARGET
. $omega/.core/PROJECTS
. $omega/.core/ARGUMENTS
. $omega/.core/UPDATER
