#!/bin/sh

# origin=~/.local/bin/bifrost
omega=~/.local/share/bifrost # Final Directory Destination of the Package Folder
. $omega/.core/ASSEMBLER $bridge_set
. $omega/.core/ASSEMBLER

start () {
    #sudoreq
    clear
    logo
    print_version
    target_data
    menu
    menu_select
}

#cd ../share/Bifrost
#origin="." # Used for debugging only
#origin=~/.local/share/Bifrost # Bifrost Path

handle_arguments "$@" # Pass all command-line arguments to the handle_arguments function
start "$@" # Bifrost Link Start
