#!/bin/sh

target_debug () {
    echo
    echo " $negative Target Debug Enabled $end"
    echo
    echo " ip $yellow2$ip$end"
    echo " ip_range $yellow2$ip_range$end"
    echo
    echo " target $yellow2$target_domain$end"
    echo " target_domain $yellow2$target_domain$end"
    echo " target_username $yellow$target_username$end"
    echo " target_password $yellow$target_password$end"
    echo 
    }

target_domain() {
    if [ -f "./TARGET" ]; then
        . "./TARGET"
        # Check if the target variable is empty
        if [ -z "$target_domain" ]; then
            echo
            printf " Enter the Target Domain or IP address/range: $red2" && read target_domain
            echo "$end"
            case "$target_domain" in
                http://*|https://*)
                    url="$target_domain"
                    ;;
                *)
                    while true; do
                        printf " Does the Target use a secure protocol (https)? $white[Y/n]$end: " && read input
                        case "$input" in
                            "y" | "Y" | "1" | "")
                                url=https://$target_domain
                                break
                                ;;
                            "n" | "N" | "2" | "")
                                url=http://$target_domain
                                break
                                ;;
                            *)
                                echo
                                echo " Please enter 'y' for yes or 'n' for no."
                                echo
                                ;;
                        esac
                    done
                    ;;
            esac
        fi
    fi

    echo
    echo "$yellow2 Establishing the bridge with the target.."
    echo

    # Rest of your code for pinging and establishing the link
    ping -c 3 "$target_domain" > /dev/null 2>&1

    # Check the exit status of the ping command
    if [ $? -eq 0 ]; then
        echo "$green2 Link Established succesfully.$end"
        sleep 3
        add_target="target_domain='$target_domain'"
        #echo "target_domain="$target_domain"" >> TARGET
        sed -i "4s/.*/$add_target/" TARGET
        echo
        #refresh_cp
        break
    else
        echo "$red Link Failed. Trying again..$end"
        sleep 3
        #target=""
        #refresh
        #target
        target_domain
    fi
}

target_prompt() {
    target_domain
    target_username
    target_password
    }

target_username() {
    if [ -f "./TARGET" ]; then
        . "./TARGET"
        # Check if the target username variable is empty
        if [ -z "$target_username" ]; then
            printf " Enter the Target Username $white[press ENTER to skip]$end: $red" && read target_username
            echo "$end"
            add_username="target_username=$target_username"
            #echo "target_username="$target_username"" >> TARGET
            sed -i "5s/.*/$add_username/" TARGET
        fi
    fi
}

target_password() {
    if [ -f "./TARGET" ]; then
        . "./TARGET"
        # Check if the target password variable is empty
        if [ -z "$target_password" ]; then
            printf " Enter the Target Password $white[press ENTER to skip]$end: $red" && read target_password
            echo "$end"
            #echo "target_password="$target_password"" >> TARGET
            add_password="target_password=$target_password"
            sed -i "6s/.*/$add_password/" TARGET
        fi
    fi
}

target_data() {
    # Check if the TARGET file exists
    if [ -f "./TARGET" ]; then
        # Source (include) the TARGET file to set the variables
        . "./TARGET"
        echo
        project_folder="$(basename "$PWD")"

        #target_debug

        if [ "$project_folder" = "$tmp_folder" ]; then
            echo " Project:  $yellow2$project_folder$end"
        else
            echo " Project:  $cyan2$project_folder$end"
        fi

        # Check if target_domain exists and print it
        if [ -n "$target_domain" ]; then
            echo " Domain:   $red2$target_domain$end"
        fi

        # Check if target_username exists and print it
        if [ -n "$target_username" ]; then
            echo " Username: $red$target_username$end"
        fi

        # Check if target_password exists and print it
        if [ -n "$target_password" ]; then
            echo " Password: $red$target_password$end"
        fi
    else
        # If TARGET file doesn't exist, print a message
        tmp    
        target_data 
        #echo "$red Target File not found. Aborting.. $end"
        #sleep 2
        #exit
    fi
}
