#!/bin/sh

print_version() {
    # Load the local version from the CONTROL file
    local_version=$(grep -o 'version="[^"]*"' $omega/.core/CONTROL | sed 's/version="//;s/"//')

    # Define the URL of the remote CONTROL file
    remote_url="https://raw.githubusercontent.com/yonasuriv/Bifrost/main/.core/CONTROL"

    # Function to fetch the remote version
    get_remote_version() {
        # Use curl to fetch the remote CONTROL file and extract the version value
        remote_version=$(curl -s "$remote_url" | grep -o 'version="[^"]*"' | sed 's/version="//;s/"//')
        echo "$remote_version"
    }

    # Compare the local and remote versions
    compare_versions() {
        local_version="$1"
        remote_version="$2"

        if [ "$local_version" = "$remote_version" ]; then
            echo
            echo "$dim Bifrost Link Version: $local_version$end $green2[UP TO DATE]$end"
        elif [ "$local_version" \> "$remote_version" ]; then # This is due to the cache timing to curl from github
            echo
            echo "$dim Bifrost Link Version: $local_version$end $green2[UP TO DATE]$end"
        else
            echo
            echo "$dim Bifrost Link Version: $local_version$end $yellow2[NEW UPDATES AVAILABLE $remote_version]$end"
        fi
    }

    # Fetch the remote version
    remote_version=$(get_remote_version)

    # Compare the versions
    compare_versions "$local_version" "$remote_version"
}

update_start() {
    rm $omega
    git clone https://github.com/yonasuriv/bifrost.git $omega > /dev/null 2>&1 && cd bifrost && sh LINK && cd - > /dev/null 2>&1
    #git clone https://github.com/yonasuriv/bifrost.git > /dev/null 2>&1 && cd bifrost && sh LINK > /dev/null 2>&1
    #. $origin/.core/CONTROL
}

force_update() {
    update_start
}

update() {
    # Load the local version from the CONTROL file
    local_version=$(grep -o 'version="[^"]*"' $omega/.core/CONTROL | sed 's/version="//;s/"//')

    # Define the URL of the remote CONTROL file
    remote_url="https://raw.githubusercontent.com/yonasuriv/Bifrost/main/.core/CONTROL"

    # Function to fetch the remote version
    get_remote_version() {
        # Use curl to fetch the remote CONTROL file and extract the version value
        remote_version=$(curl -s "$remote_url" | grep -o 'version="[^"]*"' | sed 's/version="//;s/"//')
        echo "$remote_version"
        }

    # Compare the local and remote versions
    compare_versions() {
        local_version="$1"
        remote_version="$2"

        if [ "$local_version" = "$remote_version" ]; then
            echo "$green Bifrost Link is currently in the last version ($local_version).$end"
        elif [ "$local_version" \> "$remote_version" ]; then # This is due to the cache timing to curl from github
            echo "$green Bifrost Link is currently in the last version ($local_version).$end"
        else
            echo " Local version $cyan2($local_version)$end is different from remote version $yellow2($remote_version)$end."
            echo 
            echo "$dim Initializing Bifrost Link Updater..$end"
            sleep 2
            echo
            update_start
            echo "$green2 Bifrost Link successfully updated to the last version. $end"
        fi
        }

    # Fetch the remote version
    remote_version=$(get_remote_version)

    # Compare the versions
    compare_versions "$local_version" "$remote_version"
    }
